### ISSUE TITLE
undefined reference / LINUX compilation

### ISSUE THREAD

**Issue by joyo44** [jxjo/Xoptfoil-JX#15]
Hi Jochen,
i cloned the repository and tried to compile under Linux. Failed with some undefined references:

CMakeFiles/MYOBJLIB.dir/src/fortran/os_util.f90.o: In function `__os_util_MOD_print_colored_windows':
os_util.f90:(.text+0x5d): undefined reference to `GetStdHandle'
os_util.f90:(.text+0x6b): undefined reference to `GetConsoleScreenBufferInfo'
os_util.f90:(.text+0x7a): undefined reference to `SetConsoleTextAttribute'
os_util.f90:(.text+0xfc): undefined reference to `SetConsoleTextAttribute'
collect2: error: ld returned 1 exit status

BTW, huge improvements you made to Xoptfoil, thanks.

John

**Comment by jxjo** [comment]
Hi John,
thanks for the feedback and the issue! 

Unfortunately I do not have LINUX so it's a little difficult for me to analyze. Maybe you can support? 
It seems that the precompiler directive "#ifdef UNIX" does not work...
Did you use the make file from this repository? Here I added the compiler flag "-cpp" to activate the pre compiler.
I'm not sure if the directive "#ifdef UNIX" also works in an LINUX environment? It should ...

Thank you and regards
Jochen

**Comment by jxjo** [comment]
... forgot to say:

- currently the escape sequences for colored terminal output for LINUX are not implmented
- the LINUX command for creating a subdirectory is not implemented. So the creation for the polars subdirectory will fail ..

Sorry! But this should be a minor thing to implement if you (somebody) could test it.

**Comment by joyo44** [comment]
Hi Jochen,

sorry, i have no experience with compiling for mixed OS. 

Normally Gfortran should support the derictives __linux__, __linux, __unix__ and __unix. I tried that and inluded an false statement behind the '#ifdef' and the compiler always jumped to WINDOWS  and popped up with an error. Then I compiled os_utils allone and got the warning
Illegal preprocessor directive - very strange. 

I have no idea, what's going on - may be Daniel Prosser can help.

Kind regards and stay healthy.

John

**Comment by jxjo** [comment]
Hi John,
... I think a got a solution (maybe not the best). Add an additional gfortran compiler option to set the precompiler macro: "-dUNIX=1". 
You'll find it in the updated CMakeLists.txt.
I'll provide later the colored output for UNIX/LINUX. It would be great, if could test it.
Thanks!
And regards - and yes, stay healthy!
Jochen

**Comment by joyo44** [comment]
Hi Jochen,
that works! I run an example without any problems.

Sure I can test the changes for LINUX.

Regards,
John

**Comment by jxjo** [comment]
Hi John,
with the lastest commit there should be some color in the show_details mode like this 

![grafik](https://user-images.githubusercontent.com/58261241/78466972-1c82cf80-7708-11ea-9915-83230166ad6b.png)

Thanks for your support!

Jochen

**Comment by joyo44** [comment]
Hi Jochen,
looks like your latest commit works:

![grafik](https://user-images.githubusercontent.com/63097303/78472030-012eb900-7736-11ea-8e19-3e521230108c.png)

John

**Comment by jxjo** [comment]
... uff! ;-) 
John, thanks again. If you have any further suggestions please go ahead...
