### ISSUE TITLE
xoptfoil-visualizer-jx.py: read_airfoil_polars return error

### ISSUE THREAD

**Issue by joyo44** [jxjo/Xoptfoil-JX#18]
Hi Jochen,

the line #130 "return x, y, maxt, xmaxt, maxc, xmaxc, ioerror"
should be changed to: "return x, y, maxt, xmaxt, maxc, xmaxc, ioerror, deriv2, deriv3"
to prevent an exeption in case of an IOError.

regards,
John

**Comment by jxjo** [comment]
Hi John,
... very good - thanks! I just fixed it ...
In which case did you get the ioerror?

regards
Jochen

**Comment by joyo44** [comment]
... I just mistyped the case name ;-)

**Comment by jxjo** [comment]
You are really daring ...!
;-)
