### ISSUE TITLE
XFoil_Worker: extend max. number of characters for command-line arguments

### ISSUE THREAD

**Issue by Matthias231** [jxjo/Xoptfoil-JX#21]
Please extend the maximum  possible number of characters per argument from 80 (?) to 255.
This will be necessary for call of XFoil_worker from strak_machineV2.py

**Comment by jxjo** [comment]
... this is crazy! 
;-) 
Is it because of subdirectories? Better have an additional arugment to set a (working) directory?

**Comment by Matthias231** [comment]
Yes, that's exactly the reason. 

Yes, an additional argument to set a working directory would be a good idea and also would solve other potential problems. 

In my case it would completely solve the problem, but the working-directory in my special case needs 77 characters and so is very close to the limit.

So I if it is possible to implement an additional argument with more that 80 characters I would suggest to use 255 characters to have some space for the future

**Comment by jxjo** [comment]
ok! Which option should use this working directory? 
-i input file 
-a airfoil
-o output file prefix 
The polars are already generated in the subdirectory <output file prefix>_polars. Would it be "doppel gemoppelt" ;-) ?

**Comment by Matthias231** [comment]
Hi,

- I would suggest to use the working directory for all the options, so everything is read / created automatically inside the working directory. 
Just as if XFoil_worker.exe would have been started inside the working directory.

- It should still be possible / tolerated to prepend a further sub-directory to the options, just as it is implemented at the moment (no change). 
So e.g. the option -i /ressources/myInputs.txt should still be possible and will read "myInputs.txt" from subfolder "ressources" inside the working directory

- Generating the polars: I think generating the polars inside a subdirectory inside the working directory is o.k. (no change)

**Comment by Matthias231** [comment]
Hi, just pulled the repo, works fine now!

**Comment by jxjo** [comment]
.. I'll close this issue. Let's see if we still need the working dir.
