### ISSUE TITLE
Xoptfoil:  extend namelist operating_conditions

### ISSUE THREAD

**Issue by Matthias231** [jxjo/Xoptfoil-JX#22]
For strak_machineV2 it will be necessary to tolerate (not necessarily evaluate) the namelist-variable "name" inside the namelist "operating_conditions".
This will be needed to assign the different oppoints to the "purpose" they are used for and automatically adapt the oppoints to a given root-airfoil.

**Comment by jxjo** [comment]
... I'm not sure if I undestand it... Is it to "tag" an op-point? --> Better use hashtags in a comment?

**Comment by Matthias231** [comment]
Hi, this was my first thought ;-), but in strak_machineV2.py a ready-to-use namelist-parser is used to transform the Fortran-Namelist (predefined input-file) into a python-dictionary and vice-versa. 

The comments get lost in this transformation.
Another reason is "robustness", the name / purpose of the operating Point shall be structurally "bound" to the Op-point and then automatically appear in the python-dictionary inside strak_machineV2. 

Let's say this solution is a little bit like the "helper" oppoint ;-), that in my opinion is a good and appropriate solution. 

The Xoptfoil implementation shall be tolerant, so for Xoptfoil no matter if the "name"  appears in the namelist, or not, to be compatible to older inputfile versions.

For strak_machineV2 it will be a mandatory namelist-variable.

**Comment by jxjo** [comment]
... no more needed...
