### ISSUE TITLE
strakmachine_configurator: new development

### ISSUE THREAD

**Issue by Matthias231** [jxjo/Xoptfoil-JX#24]
Please develop "strakmachine_configurator" (this is a "huge one" ;-), maybe we need some additional "man-power")

- The software "strak_machine_configurator" (probably a python-script) shall provide a graphical user-interface (GUI) to setup and manage a strak-machine project.

- All user input shall be collected / managed via the graphical user interface.

- Examples for User-Input:
          1. Name of the project
          2. Type of Strak (e.g. Acro, F3F, Glider, etc.) 
          3. Choice / name of the seed- /root- airfoil (e.g file-dialog appears)
          4. Number of Airfoils to be created
          5. List of chord-lengths and / or list of Re-Numbers to be entered
          6. Optional: A list of airfoilnames can be entered for the airfoils that will be created
          7. As an alternative for 5: choice of a predefined wing in XML-Format (file-dialog) that was created with XFLR5  or planform-creator.py
          8. Some further options (optimization settings etc.)
          9. ….

- With the given user-input, it shall be possible to create a configuration-file ("strakdata.txt") in .json format,  that contains the neccessary parameters for "strak_machineV2.py"

- It shall be possible to store all user-input in a file and also possible to read from file

- If possible, "QT for python" shall be used to provide the GUI to have a modern looking user-interface. Therefore Python 3 is needed, because Python 2.7 will not be supported by QT for python anymore. 

- Please check, if all existing python-scripts (e.g. xoptfoil_visualizer-jx.py, particle-viewer.py strak_machineV2.py etc.) will run on Python 3. If not, please update the scripts

**Comment by jxjo** [comment]
... maybe this isn't needed anymore because of X5optfoil... ;-)
