### ISSUE TITLE
reviewing smoothing results

### ISSUE THREAD

**Issue by Roehrich** [jxjo/Xoptfoil-JX#25]
Hi,

I was trying to visualize the smoothing results of the XFoil-worker. In the Readme of the example it is written that "You may visualize the results by starting the visualizer with 

	xoptfoil_visualizer-jx.py -c HD45-smoothed -o 1 "
This command will look for the project "HD45-smoothed" and show result #1.
The script is therefore looking for file "HD45-smoothed_design_coordinates.dat" but this file is not written by the Xfoil_worker.
How can this be fixed?

**Comment by jxjo** [comment]
Hi,
(sorry for the late answer)
... the worker needs the option "-v" to create the file for the visualizer (please have a look into worker documentation)

**Comment by Roehrich** [comment]
Thanks a lot for clarification - I overlooked this option in the documentation...
