### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by marcovanderbijl** [jxjo/Xoptfoil-JX#26]
Compilation fails on Linux Mint 19.1 for me with a whole list of the following type of error; would you be able to give me help on how to get the build to work? 
`
[ 78%] Building Fortran object CMakeFiles/MYOBJLIB.dir/src/fortran/xfoil_deps/xfoil_aero.f.o
/home/marco/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gfortran -DPACKAGE_VERSION=\"1.61beta\"  -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -pipe -O3 -fopenmp -DOPENMP=1 -cpp -DUNIX=1    -fdefault-real-8 -c /home/marco/Programs/Xoptfoil-master/src/fortran/xfoil_deps/xfoil_aero.f -o CMakeFiles/MYOBJLIB.dir/src/fortran/xfoil_deps/xfoil_aero.f.o
/home/marco/Programs/Xoptfoil-master/src/fortran/xfoil_deps/xfoil_aero.f:63:25:

       SUBROUTINE PSILIN(I,XI,YI,NXI,NYI,PSI,PSI_NI,GEOLIN,SIGLIN)
                         1
Error: Symbol 'i' at (1) has no IMPLICIT type
`

**Comment by jxjo** [comment]
Hi Marco (?),

... the problem arises with the compiler flag "-fimplicit-none". In old Fortran programs like xfoil it was quite common that implicit types whre used. All variables beginning with i, j, k, l were integers...
The question is, how this compiler option comes into your make file (?) - it is not in the cmake definition file cmakeList.txt..
If you are able to remove this option somehow, it will work.

Hope this helps.

regards

Jochen

**Comment by jxjo** [comment]
... seems to work ...
