### ISSUE TITLE
build not working on Linux / Fedora 34

### ISSUE THREAD

**Issue by Pulsar07** [jxjo/Xoptfoil-JX#28]
When running the build script build_linux.sh the loader gives this error:
".... can not be used when making a shared object; recompile with -fPIC"

In my environment setting the -fPIC option for position independent code in the file CMakeLists.txt solves the problem.
```
if (Fortran_COMPILER_NAME MATCHES "gfortran")
 set (CMAKE_Fortran_FLAGS_RELEASE "-fPIC -O3 ${OPENMP_FLAG} -cpp ${OS_FLAG} ${STATIC_FLAG}")
```

Regards 
Rainer

**Comment by jxjo** [comment]
...thanks Rainer. 
I will add the flag to the build script...
