### ISSUE TITLE
Running the examples in "Matching foils" does not work

### ISSUE THREAD

**Issue by Pulsar07** [jxjo/Xoptfoil-JX#29]
when running the examples with the input files 
Matching foils/imatch-camb-thick.txt
Matching foils/imatch-hicks-henne.txt
 the error is given:
` Error: namelist operating_conditions is required and was not found in input file.`

Adding an empty operating_conditions block in the input files  solves the problem
```
&operating_conditions
/ 

```

**Comment by jxjo** [comment]
...oh - yes. Sorry for this bug.

I also noticed it -it's already fixed in the sources...
