### ISSUE TITLE
foil_worker don't accept any input for mach number

### ISSUE THREAD

**Issue by emdotjay** [jxjo/Xoptfoil-JX#32]
Neither the helper for polar inputs, nor the foil_worker don't accept any input to specify the mach number.
But the xoptfoil-jx do accept a mach number specification:

e.g: mach(1) = 0.55

**Comment by jxjo** [comment]
Hi,
.. this is right. I'll fix it in the next version. 
Are you able to compile by yourself?

**Comment by emdotjay** [comment]
Hi,

sorry but I'm not able to compile it by my self.

And at the moment I'm not sure if xoptfoil-jx also accept the mach number specification.

I use xoptfoil for a aircraft design class.
The objective function is reducing the overall drag in the range of 0.6 < CL 0.8 at Re=2E7 and Ma=0.55.
Your code produce a "smoother" geometry than xoptfoil, but the former codebasis converge fast to a result.

**Comment by jxjo** [comment]
Hi,
... I'll have a look on the Mach number implementation (never used it before) and fix it in the next version ...
regards
Jochen

**Comment by jxjo** [comment]
... sorry - it took a while ... 

Optimization and polar generation with Mach numbers are now supported in Xoptfoil2 - see [here](https://github.com/jxjo/Xoptfoil2/releases/tag/v1.0.1)
