### ISSUE TITLE
Customizing Xfoil for Xoptfoil-JX

### ISSUE THREAD

**Issue by ateny112** [jxjo/Xoptfoil-JX#33]
Hi i was looking for it but i think that for now there is no option to to change for example boundary layer parameters for airfoil evaluation in xoptfoil-jx. (that's a pitty, because with it, the program would become much more useful) But from what I understand when the program runs there has to be a moment where settings are put to a file that is then fed to xfoil, so would it be possible to change a few lines of code on my computer to set custom parameters in vpar for example? Could you give me a hint in which file to look for this part of code?

**Comment by jxjo** [comment]
Hi,
what bl paramter you are thinking of? 
All typical vpar parameters can be set in the 'xfoil_run_options' namelist of the input file.
(xfoil is integrated within Xoptfoil via direct api call. So there no files involved)
regards
Jochen

**Comment by ateny112** [comment]
Hi, I typically work with G-beta constants and other unfortunately not listed in the 'xfoil_run_options' namelist. Would it be possible to give me a hint how (and which file) to modify the source code in order to tweak them?

**Comment by jxjo** [comment]
Hi,

... do you mean these parms? 


```
      SCCON = 5.6
      GACON = 6.70
      GBCON = 0.75
      GCCON = 18.0
      DLCON =  0.9
```
They are definied in` xfoil_aero.f` ...

**Comment by ateny112** [comment]
This is exactly what I needed, Thanks a lot!
