### ISSUE TITLE
Feature request: minimum-cp constraint or penalty

### ISSUE THREAD

**Issue by klausbu** [jxjo/Xoptfoil-JX#34]
Feature request:

Is there a way to set minimum-cp (from the xflr OpPoint view  F5) as a constraint or penalty to be above a certain value (maybe for a defined AOA range)?

This can be relevant for wings, stabilizers... operating under water.

**Comment by jxjo** [comment]
(Xoptfoil-JX development ended --> please go to [Xoptfoil2](https://github.com/jxjo/Xoptfoil2))

Hello, 

Could you explain a little what you like to achieve (or the use case)? 

Is it to limit the suction peak? In this case - as the suction peak depends mainly on the leading edge curvature - it would be most easy to limit the curvature at leading edge ... 

regards

Jochen

**Comment by klausbu** [comment]
Hello Jochen,

There has been a discussion about it and its implementation related to the original xoptfoil but the implementation never happened:

See: https://www.rcgroups.com/forums/showthread.php?2095696-XoptFoil-airfoil-optimization-with-XFoil/page29   #431, #432

The limitation of the suction peak is one aspect but the cp-min can also be above the back of the foil, in this case a "rooftop" can be a result, see picture under #432 on the very right. 

regards,

Klaus

PS: Should be move the discussion to  [Xoptfoil2](https://github.com/jxjo/Xoptfoil2) ?

**Comment by jxjo** [comment]
Hello Klaus, 

... yes - would you be so kind and move the issue to Xoptfoil2?

Meanwhile I'll have a look at rcgroups ...

regards
Jochen

**Comment by jxjo** [comment]
moved to Xoptfoil2
